const EventHeads = [
    {
        bgImg: "bg-siril",
        name: "Ashwin K V",
        event: "Coding",
        contact: "9567454484",
        email: "ashwinkv.akv@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Iyola Gloria Dsilva ",
        event: "Coding",
        contact: "6362115410",
        email: "iyodsilva18@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Joel James",
        event: "Gaming (Closed)",
        contact: "9108770492",
        email: "jestinejames4@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Sonal Riva Gonsalves",
        event: "Gaming (Closed)",
        contact: "7204206754",
        email: "sonalgonsalves174@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Laniel Charles Dias",
        event: "Gaming (Open)",
        contact: "7892849393",
        email: "dlaniel133@gmail.com",
    },
    {
        bgImg: "bg-royal",
        name: "Frank Stalin Dsouza",
        event: "Gaming (Open)",
        contact: "7022678809",
        email: "stalindsouza487@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Vivian Dsouza",
        event: "IT Expo",
        contact: "8073425253",
        email: "viviandsouza923@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Lishma",
        event: "IT Expo",
        contact: "7899026237",
        email: "lishma2003@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Deepak Amin",
        event: "Icongnito",
        contact: "8618000577",
        email: "deep9845855586@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Pragati Jayakumar",
        event: "Icongnito",
        contact: "7019727270",
        email: "pragathishetty841@gmail.com",
    },
    {
        bgImg: "bg-neha",
        name: "Bhushan Bangera",
        event: "IT Manager",
        contact: "7204624083",
        email: "bhushanabangera687@gmail.com",
    },
    {
        bgImg: "bg-neha",
        name: "Elkan Pais",
        event: "IT Manager",
        contact: "9483916991",
        email: "elkabrian162@gmail.com ",
    },
    {
        bgImg: "bg-siril",
        name: "Mahima P",
        event: "Quiz",
        contact: "8317349105",
        email: "mahimaparamashivam815@gmail.com",
    },
    {
        bgImg: "bg-siril",
        name: "Glen",
        event: "Quiz",
        contact: "459827345",
        email: "randommail@gmail.com",
    },
    {
        bgImg: "bg-ashwin",
        name: "Anvisha Gladline Dsouza",
        event: "Web Designing",
        contact: "7022308033",
        email: "dummymail@gmail.com",
    },
    {
        bgImg: "bg-delbin",
        name: "Delbin George",
        event: "Web Designing",
        contact: "9539361202",
        email: "imdelbingeorge@gmail.com",
    },
];

export default EventHeads;
