const EventHeads = [
    {
        bgImg: "bg-ashwin",
        name: "Ashwin K V",
        event: "Coding",
        contact: "9567454484",
        email: "ashwinkv.akv@gmail.com",
    },
    {
        bgImg: "bg-iyola",
        name: "Iyola Gloria Dsilva ",
        event: "Coding",
        contact: "6362115410",
        email: "iyodsilva18@gmail.com",
    },
    {
        bgImg: "bg-joel",
        name: "Joel James",
        event: "Gaming (Closed)",
        contact: "9108770492",
        email: "jestinejames4@gmail.com",
    },
    {
        bgImg: "bg-sonal",
        name: "Sonal Riva Gonsalves",
        event: "Gaming (Closed)",
        contact: "7204206754",
        email: "sonalgonsalves174@gmail.com",
    },
    {
        bgImg: "bg-nihal",
        name: "Nihal Amin",
        event: "Gaming (Closed)",
        contact: "8123942381",
        email: "nihalamin16@gmail.com",
    },
    {
        bgImg: "bg-laniel",
        name: "Laniel Charles Dias",
        event: "Gaming (Open)",
        contact: "7892849393",
        email: "dlaniel133@gmail.com",
    },
    {
        bgImg: "bg-frank",
        name: "Frank Stalin Dsouza",
        event: "Gaming (Open)",
        contact: "7022678809",
        email: "stalindsouza487@gmail.com",
    },
    {
        bgImg: "bg-jaslyn",
        name: "Jaslyn Samantha D'Souza",
        event: "Gaming (Open)",
        contact: "8951647296",
        email: "jaslyn290@gmail.com",
    },
    {
        bgImg: "bg-vivian",
        name: "Vivian Dsouza",
        event: "Exi-Bit",
        contact: "8073425253",
        email: "viviandsouza923@gmail.com",
    },
    {
        bgImg: "bg-lishma",
        name: "Lishma Menezes",
        event: "Exi-Bit",
        contact: "7899026237",
        email: "lishma2003@gmail.com",
    },
    {
        bgImg: "bg-deepak",
        name: "Deepak Amin",
        event: "Incognito",
        contact: "8618000577",
        email: "deep9845855586@gmail.com",
    },
    {
        bgImg: "bg-pragathi",
        name: "Pragathi Jayakar",
        event: "Incognito",
        contact: "7019727270",
        email: "pragathishetty841@gmail.com",
    },
    {
        bgImg: "bg-bushan",
        name: "Bhushan Bangera",
        event: "Tech Xtreme",
        contact: "7204624083",
        email: "bhushanabangera687@gmail.com",
    },
    {
        bgImg: "bg-elkan",
        name: "Elkan Pais",
        event: "Tech Xtreme",
        contact: "9483916991",
        email: "elkabrian162@gmail.com ",
    },
    {
        bgImg: "bg-mahima",
        name: "Mahima P",
        event: "Quizathon",
        contact: "8317349105",
        email: "mahimaparamashivam815@gmail.com",
    },
    {
        bgImg: "bg-kavya",
        name: "Kavya Pandit",
        event: "Quizathon",
        contact: "8105520688",
        email: "kavyapandit81@gmail.com",
    },
    {
        bgImg: "bg-anvisha",
        name: "Anvisha Gladline Dsouza",
        event: "Web Odyssey",
        contact: "7022308033",
        email: "anvishadsouza30@gmail.com",
    },
    {
        bgImg: "bg-delbin",
        name: "Delbin George",
        event: "Web Odyssey",
        contact: "9539361202",
        email: "imdelbingeorge@gmail.com",
    },
];

export default EventHeads;
