const OtherHeads = [
    {
        bgImg: "bg-amy",
        name: "Amy Mascarenhas",
        event: "Reception Committee Head",
        contact: "8867278757",
        email: "amymascarenhas6@gmail.com",
    },
    {
        bgImg: "bg-shaina",
        name: "Shaina Emily Rebello ",
        event: "Reception Committee Head",
        contact: "8123324331",
        email: "shaina.rebello18@gmail.com",
    },
    {
        bgImg: "bg-varshit",
        name: "Varshit B.R",
        event: "Public Relation Head",
        contact: "7892232294",
        email: "varshithforreal@gmail.com",
    },
    {
        bgImg: "bg-sayhan",
        name: "Sayhan Sameer",
        event: "Public Relation Head",
        contact: "9683707451",
        email: "",
    },
    {
        bgImg: "bg-varshitha",
        name: "B H varshitha",
        event: "Finance Head",
        contact: "7769032681",
        email: "varshiharish@gmail.com",
    },
    {
        bgImg: "bg-geethika",
        name: "Geetika Bharat Bisht",
        event: "Finance Head",
        contact: "7349408965",
        email: "geetikabhist@gmail.com",
    },
    {
        bgImg: "bg-charan",
        name: "Charan KT ",
        event: "Food Committee Head",
        contact: "9902875263",
        email: "charanktc313@gmail.com",
    },
    {
        bgImg: "bg-prenisha",
        name: "Prenisha J Amin",
        event: "Food Committee Head",
        contact: "9353428190",
        email: "prenishaamin@gmail.com",
    },
    {
        bgImg: "bg-vaishnavi",
        name: "Vaishnavi J",
        event: "Decoration Head",
        contact: "8296579101",
        email: "jvaishnavi931@gmail.com",
    },
    {
        bgImg: "bg-brian",
        name: "Brian Dcosta",
        event: "Decoration Head",
        contact: "9591605596",
        email: "dcostabrian17@gmail.com",
    },
    {
        bgImg: "bg-robin",
        name: "Robin Joseph dsouza",
        event: "Arrangement Committee Head",
        contact: "9591605596",
        email: "dsouzar175@gmail.com",
    },
    {
        bgImg: "bg-vignesh",
        name: "Vignesh BS",
        event: "Arrangement Committee Head",
        contact: "8296586740",
        email: "vigneshbs628@gmail.com",
    },
    {
        bgImg: "bg-swasthi",
        name: "Swasthi Umesh Bhandary",
        event: "Prize & Certificate",
        contact: "8197022793",
        email: "swasthibhandary1b@gmail.com",
    },
    {
        bgImg: "bg-maithri",
        name: "Maithri MN",
        event: "Prize & Certificate",
        contact: "7483186817",
        email: "mnmaithri48@gmail.com",
    },
    {
        bgImg: "bg-shibin",
        name: "Shibin SK",
        event: "Photography & Editing",
        contact: "9633389789",
        email: "shibinsreedhar@gmail.com",
    },
    {
        bgImg: "bg-praneeth",
        name: "Praneeth M",
        event: "Photography & Editing",
        contact: "8075493943",
        email: "praneethm181@gmail.com",
    },
    {
        bgImg: "bg-rohan",
        name: "Rohan Jacob",
        event: "Graphic Designing",
        contact: "6282292458",
        email: "rohan.jxcob@gmail.com",
    },
    {
        bgImg: "bg-suprath",
        name: "Suprath P S",
        event: "Graphic Designing",
        contact: "9731745319",
        email: "suprathps@gmail.com",
    },
];

export default OtherHeads;
